version: '3.8'

services:
  api-mvc:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/venv
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --reload
